networks:
  pub:

services:
  beaconprod:
    restart: always
    build:
      context: .
    container_name: beaconprod
    ports:
      - "5050:5050"
    entrypoint: ["python", "-m", "beacon"]
    volumes:
      - ./beacon/logs/logs.log:/beacon/logs/logs.log
      - ./beacon/conf/conf.py:/beacon/conf/conf.py
      - ./beacon/permissions:/beacon/permissions
    networks:
      - pub

  db:
    image: mongo:5
    command: --wiredTigerCacheSizeGB 4
    #command: --wiredTigerCacheSizeGB 4 --sslMode requireSSL --tlsCertificateKeyFile test-server1.pem --tlsCAFile test-ca.pem
    hostname: mongo
    container_name: mongoprod
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: beacon
    volumes:
      - ./beacon/connections/mongo/mongo-init/:/docker-entrypoint-initdb.d/:ro
      - ./beacon/connections/mongo/data/:/data
      - ./beacon/connections/mongo/data/db:/data/db
      - ./beacon/connections/mongo/data/configdb:/data/configdb
      - ./beacon/connections/mongo/data/caseLevelData:/data/caseLevelData
      #- ./test-server1.pem:/test-server1.pem
      #- ./test-ca.pem:/test-ca.pem
      #- ./test-client.pem:/test-client.pem
    networks:
      - pub
    #command: --verbose
