apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-beacon-service
  annotations:
    # cloud.google.com/backend-config: '{"ports": {"5050": "{{ .Values.ingress.backendConfigName }}"}}'
    cloud.google.com/backend-config: '{"default": "{{ .Release.Name }}-health-config"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: {{ .Values.beacon.service.type }}
  selector:
    app: {{ .Values.beacon.selectorLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.beacon.service.port }}
      targetPort: {{ .Values.beacon.service.port }}
	  {{- if and (eq .Values.beacon.service.type "NodePort") .Values.beacon.service.nodePort }}
      nodePort: {{ .Values.beacon.service.nodePort }}
	  {{- end }}
