apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mongodb.config.initScriptConfigMap }}
data:
  init.js: |
{{- .Files.Get "files/init.js" | nindent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.beacon.config.configMapName }}
data:
  conf.py: |
{{- .Files.Get "files/conf.py" | nindent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.beacon.config.permissionsMapName }}
data:
  datasets_permissions.yml: |
{{- .Files.Get "files/datasets_permissions.yml" | nindent 4 }}
