{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
	name: {{ .Values.mongodb.secret.name | default (printf "%s-secret" .Release.Name) }}
type: Opaque
stringData:
	MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.secret.username }}
	MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.secret.password }}
{{- end -}} 
