test:
  public:
    default_entry_types_granularity: boolean
    entry_types_exceptions:
      - individual: record
    user-list:
      - user_e-mail: jane.smith@beacon.ga4gh
        default_entry_types_granularity: count
        entry_types_exceptions:
          - individual: record

gnomad_exome_v2.1.1:
  public:
    default_entry_types_granularity: record
    entry_types_exceptions:
      - individual: record

gnomad_joint_v4.1:
  public:
    default_entry_types_granularity: record
    entry_types_exceptions:
      - individual: record

EGAD00001007774:
  public:
    default_entry_types_granularity: record
    entry_types_exceptions:
      - individual: record

CINECA_synthetic_cohort_EUROPE_UK1:
  registered:
    default_entry_types_granularity: count
    entry_types_exceptions:
      - cohort: boolean

AV_Dataset:
  controlled:
    default_entry_types_granularity: boolean
    entry_types_exceptions:
      - individual: boolean
    user-list:
      - user_e-mail: jane.smith@beacon.ga4gh
        default_entry_types_granularity: boolean
        entry_types_exceptions:
          - individual: boolean
# Agafar com a identificador d'usuari el que digui la OIDC spec.
