beacon:
  image:
    repository: "australia-southeast1-docker.pkg.dev/beacon-guardians/beacon-images/beacon-app"
    tag: "v1"

  service:
    nodePort: null

ingress:
  enabled: true
  host: "dev.beacon.dsp.garvan.org.au"
  backendConfigName: "beacon-dev-iap-config"
  managedCertName: "beacon-dev-ssl-cert"
  allowedPaths:
    - path: /api
      pathType: Exact

    - path: /api/cohorts
      pathType: Prefix

localDev:
  createHostPathPV: false

mongodb:
  persistence:
    storageClass: "standard-rwo"
