database_host = 'mongo-service' #'host.docker.internal'
database_port = 27017
database_user = 'root'
database_password = 'example'
database_name = 'beacon'
database_auth_source = 'admin'
database_certificate = ''
database_cafile = ''
database_cluster = False
